sudo: True
matrix:
  include:
  
  - language: node_js
    node_js: 6
    python: 2.7
    before_install:
      - npm i -g npm
      - pip install --upgrade pip
    install:
      - pip install -r requirements.txt
      - npm install
      - cypress install
    script: 
      - python application.py
      - $(npm bin)/cypress run
      
cache:
  directories:
    - ~/.npm
    - node_modules


 
