matrix:
  include:
  - language: python
    python: 2.7
  - language: node_js
    node_js: 6
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
  - cypress install
script:
  - python application.py
  - $(npm bin)/cypress run
