matrix:
  include:
  
  - language: node_js
    node_js: 6
    python: 2.7
    install:
      - pip install flask
      - pip freeze > requirements.txt
      - npm install
      - cypress install
    script: 
      - python application.py
      - $(npm bin)/cypress run
      
cache:
  directories:
    - ~/.npm
    - node_modules


 
