language: python
sudo: false
python: 2.7
env: PYTHONPATH=.
before_install:
  - npm i -g npm
install:
  - pip install -r requirements.txt
  - npm install
  - npm ci
  - npm install wait-on
  - cypress install
script:
  - python application.py -- --silent &
  - wait-on http://localhost:5000
  - $(npm bin)/cypress run
cache:
  directories:
    - ~/.npm
    - node_modules

