matrix:
  include:
  - language: python
    python: 2.7
    install:
      - pip freeze > requirements.txt
  - language: node_js
    node_js: 6
    install:
      - npm install
      - cypress install
cache:
  directories:
    - ~/.npm
    - node_modules

script:
  - python application.py
  - $(npm bin)/cypress run
