language: python
sudo: false
python: 2.7
env: PYTHONPATH=.
install:
  - pip install -r requirements.txt
  - npm ci
before_script:
  python application.py -- --silent &
script:
  - $(npm bin)/cypress run
cache:
  directories:
    - ~/.npm
    - node_modules

