language: node_js,python
node_js:
  - 6
python:
  - 2.7
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
  - npm install cypress --save-dev
  - cypress install
  - pip freeze > requirements.txt
script:
  - $(npm bin)/cypress run
