language: node_js
node_js: 6
python: 2.7
install:
  - pip install -r requirements.txt
  - npm install
  - cypress install
script:
  - npm run ci
cache:
  directories:
    - ~/.npm
    - node_modules



