matrix:
  include:
  - language: python
    python: 2.7
    install:
      - pip install flask
      - pip freeze > requirements.txt
      - npm install
      - cypress install
    script: 
      - $(npm bin)/cypress run

cache:
  directories:
    - ~/.npm
    - node_modules


 
