matrix:
  include:
  - language: python
    python: 2.7
    install:
      - pip install -r requirements.txt
  - language: node_js
    node_js: 6
    install:
      - npm install
      - cypress install
    script:
      - npm run ci
cache:
  directories:
    - ~/.npm
    - node_modules



